# Generated by Django 4.1.3 on 2022-12-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assignee',
        ),
    ]
