# Generated by Django 4.1.3 on 2022-11-26 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='member',
            new_name='team_member',
        ),
    ]
