# Generated by Django 4.1.3 on 2022-11-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
