# Generated by Django 4.1.3 on 2022-12-16 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(default='19:45'),
        ),
    ]
